unit ThreadMsgConstants;

interface

const
  THREAD_MSG_RESET_UI = 0;
  THREAD_MSG_SHOW_ERROR = 1;
  THREAD_MSG_UPDATE_PROGRESS = 2;
  THREAD_MSG_UPDATE_META_NAME = 3;
  THREAD_MSG_UPDATE_META_BITRATE = 4;
  THREAD_MSG_UPDATE_META = 7;
  THREAD_MSG_STATUS_UPDATE = 8;
  THREAD_MSG_REPAINT_RADIO_LIST = 9;
  THREAD_MSG_STOP_IMG_ANIM = 10;
  THREAD_MSG_DOWNLOAD_LYRIC = 11;
  THREAD_MSG_START_RECORDING = 12;
  THREAD_MSG_PLAY_NEXT_SONG = 13;
  THREAD_MSG_UPDATE_LEVELS = 14;

implementation
end.

